import { Leaf, Wheat, Layers, Apple, Bean, Coffee, type LucideIcon } from "lucide-react";

export type Category = "Vegetables" | "Grains" | "Tubers" | "Fruits" | "Legumes" | "Cash Crops";

export const CATEGORY_ICON: Record<Category, LucideIcon> = {
  Vegetables:   Leaf,
  Grains:       Wheat,
  Tubers:       Layers,
  Fruits:       Apple,
  Legumes:      Bean,
  "Cash Crops": Coffee,
};

export interface Product {
  id: number;
  name: string;
  category: Category;
  farmer: string;
  farmerInitial: string;
  location: string;
  state: string;
  price: number;
  unit: string;
  qty: number;
  minOrder: number;
  rating: number;
  reviews: number;
  badge?: string;
  img: string;
  desc: string;
  harvest: string;
  quality: string;
  method: string;
  verified: boolean;
}


export const CATEGORY_COLOR: Record<Category, string> = {
  Vegetables:   "bg-emerald-100 text-emerald-700",
  Grains:       "bg-amber-100 text-amber-700",
  Tubers:       "bg-orange-100 text-orange-700",
  Fruits:       "bg-yellow-100 text-yellow-700",
  Legumes:      "bg-lime-100 text-lime-700",
  "Cash Crops": "bg-brown-100 text-stone-700",
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Tumatir (Roma Tomato)",
    category: "Vegetables",
    farmer: "Alhaji Musa Ibrahim",
    farmerInitial: "AM",
    location: "Kano, Kano State",
    state: "Kano",
    price: 380,
    unit: "kg",
    qty: 1500,
    minOrder: 50,
    rating: 4.9,
    reviews: 89,
    badge: "Fresh Harvest",
    img: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&h=400&fit=crop&auto=format",
    desc: "Premium tumatir (Roma tomatoes) freshly harvested from Kano — Nigeria's largest tomato-producing state. High sugar content and firm texture, ideal for tomato paste, jollof rice base, and fresh suya garnish. Grown without harmful pesticides. Packaged in 50kg wooden crates lined with dry grass. Traded at Dawanau International Market.",
    harvest: "2026-06-20",
    quality: "Grade A",
    method: "Organic",
    verified: true,
  },
  {
    id: 2,
    name: "Masara (White Maize)",
    category: "Grains",
    farmer: "Fatima Abubakar",
    farmerInitial: "FA",
    location: "Jos, Plateau State",
    state: "Plateau",
    price: 170,
    unit: "kg",
    qty: 5000,
    minOrder: 100,
    rating: 4.7,
    reviews: 142,
    badge: "Best Seller",
    img: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=400&fit=crop&auto=format",
    desc: "Dry masara (white maize/corn) with moisture content below 14%. Clean, sorted, and ready for milling into tuwo masara or corn flour. Available in 50kg sacks at Terminus Market, Jos. Meets Flour Mills Nigeria and NASCON volume standards. Excellent for akamu (pap) and animal feed.",
    harvest: "2026-05-15",
    quality: "Grade B+",
    method: "Conventional",
    verified: true,
  },
  {
    id: 3,
    name: "Ji Ocha (White Yam)",
    category: "Tubers",
    farmer: "Emmanuel Benson",
    farmerInitial: "EB",
    location: "Makurdi, Benue State",
    state: "Benue",
    price: 450,
    unit: "kg",
    qty: 800,
    minOrder: 50,
    rating: 4.8,
    reviews: 67,
    badge: "Premium",
    img: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop&auto=format",
    desc: "Large, firm ji ocha (white yam) from Benue — the 'Food Basket of the Nation'. Ideal for pounded yam (iyan), yam pottage (asaro), and ji mmiri oku. Minimal bruising. Packaged in 50kg crates. Varieties: Kemi, Efuru, and Amope — all highly rated in Makurdi and Onitsha markets.",
    harvest: "2026-06-01",
    quality: "Grade A",
    method: "Traditional",
    verified: true,
  },
  {
    id: 4,
    name: "Tatasai (Scotch Bonnet)",
    category: "Vegetables",
    farmer: "Aisha Kaduna",
    farmerInitial: "AK",
    location: "Zaria, Kaduna State",
    state: "Kaduna",
    price: 1200,
    unit: "kg",
    qty: 200,
    minOrder: 10,
    rating: 4.6,
    reviews: 44,
    badge: "Hot & Fresh",
    img: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&h=400&fit=crop&auto=format",
    desc: "Extra-hot tatasai (scotch bonnet pepper), bright red and fully ripe. Essential for suya pepper blend, ofe onugbu, egusi soup, and pepper soup. Sun-drying (barkono bushe) available on request at additional cost. Minimum 3-day shelf life post-harvest. Widely sourced at Zaria Central Market and Kaduna Kasuwa.",
    harvest: "2026-06-22",
    quality: "Grade A",
    method: "Organic",
    verified: true,
  },
  {
    id: 5,
    name: "Wake (Brown Cowpea)",
    category: "Legumes",
    farmer: "Ibrahim Sokoto",
    farmerInitial: "IS",
    location: "Sokoto, Sokoto State",
    state: "Sokoto",
    price: 520,
    unit: "kg",
    qty: 2000,
    minOrder: 100,
    rating: 4.9,
    reviews: 203,
    badge: "Top Rated",
    img: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop&auto=format",
    desc: "Clean, sorted wake (brown cowpea/beans) free of foreign matter. Sokoto wake is among the finest in Nigeria — uniform size and very low dirt content. Ideal for moi-moi, akara, gbegiri soup, and wake stew. Stored in cool, dry conditions. Bulk orders above 1,000kg receive 5% discount.",
    harvest: "2026-04-10",
    quality: "Grade A",
    method: "Conventional",
    verified: true,
  },
  {
    id: 6,
    name: "Ope Oyibo (Pineapple)",
    category: "Fruits",
    farmer: "Grace Nwosu",
    farmerInitial: "GN",
    location: "Onitsha, Anambra State",
    state: "Anambra",
    price: 280,
    unit: "kg",
    qty: 400,
    minOrder: 20,
    rating: 4.7,
    reviews: 38,
    badge: "Seasonal",
    img: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&h=400&fit=crop&auto=format",
    desc: "Juicy ope oyibo (pineapple) harvested at full ripeness. Perfect for fresh juice, puff-puff topping, and export. Cartons of 10–12 pieces. Harvested and dispatched same day for maximum freshness. High demand at Onitsha Main Market and Aba. Early ordering strongly advised during peak season.",
    harvest: "2026-06-18",
    quality: "Grade A",
    method: "Organic",
    verified: false,
  },
  {
    id: 7,
    name: "Koko (Dried Cocoa Beans)",
    category: "Cash Crops",
    farmer: "Peter Adeleke",
    farmerInitial: "PA",
    location: "Akure, Ondo State",
    state: "Ondo",
    price: 2800,
    unit: "kg",
    qty: 1000,
    minOrder: 200,
    rating: 4.8,
    reviews: 56,
    badge: "Export Grade",
    img: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=600&h=400&fit=crop&auto=format",
    desc: "Fermented and sun-dried koko (cocoa beans) with moisture content of 7%. Export-quality from Ondo State — Nigeria's top cocoa-producing state. NAFDAC registered. Packaged in clean jute sacks for export through Apapa Port. Sought after by international chocolate manufacturers and commodity traders.",
    harvest: "2026-05-30",
    quality: "Grade 1",
    method: "Traditional",
    verified: true,
  },
  {
    id: 8,
    name: "Afufa (Garden Egg)",
    category: "Vegetables",
    farmer: "Ngozi Okafor",
    farmerInitial: "NO",
    location: "Enugu, Enugu State",
    state: "Enugu",
    price: 320,
    unit: "kg",
    qty: 300,
    minOrder: 20,
    rating: 4.5,
    reviews: 29,
    img: "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=600&h=400&fit=crop&auto=format",
    desc: "Fresh, tender afufa (garden egg/African eggplant) from Enugu State. Essential for ofe onugbu (bitter leaf soup), ofe akwu (palm nut soup), and served with groundnut paste (ose oji) as a traditional Igbo snack. Both white (Igbo-Oji) and purple varieties available. Harvested twice weekly.",
    harvest: "2026-06-23",
    quality: "Grade B+",
    method: "Conventional",
    verified: false,
  },
  {
    id: 9,
    name: "Citta (Fresh Ginger)",
    category: "Vegetables",
    farmer: "Yunusa Kadiri",
    farmerInitial: "YK",
    location: "Kaduna, Kaduna State",
    state: "Kaduna",
    price: 950,
    unit: "kg",
    qty: 600,
    minOrder: 25,
    rating: 4.8,
    reviews: 71,
    badge: "High Demand",
    img: "https://images.unsplash.com/photo-1573883431205-98b5f10aaedb?w=600&h=400&fit=crop&auto=format",
    desc: "Premium citta (fresh ginger) from Kaduna — Nigeria supplies over 30% of global ginger. High gingerol content. Used for zobo drink, shayi (Hausa spiced tea), suya marinade, and export. Fresh and dried (citta bushe) options available. Compliant with EU and US phytosanitary import standards.",
    harvest: "2026-06-10",
    quality: "Export Grade",
    method: "Organic",
    verified: true,
  },
  {
    id: 10,
    name: "Dawa (Guinea Corn)",
    category: "Grains",
    farmer: "Halima Bello",
    farmerInitial: "HB",
    location: "Maiduguri, Borno State",
    state: "Borno",
    price: 140,
    unit: "kg",
    qty: 8000,
    minOrder: 200,
    rating: 4.6,
    reviews: 94,
    img: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=600&h=400&fit=crop&auto=format",
    desc: "Red dawa (guinea corn/sorghum), clean-threshed with low moisture content. Essential for tuwo dawa, kunu zaki (a popular northern drink), fura da nono, burukutu, and animal feed. Consistent supply year-round from Maiduguri. Large volume orders welcome for breweries and processors.",
    harvest: "2026-04-28",
    quality: "Grade A",
    method: "Conventional",
    verified: true,
  },
  {
    id: 11,
    name: "Ogede Agbagba (Plantain)",
    category: "Fruits",
    farmer: "Joseph Effiong",
    farmerInitial: "JE",
    location: "Uyo, Akwa Ibom State",
    state: "Akwa Ibom",
    price: 230,
    unit: "kg",
    qty: 1200,
    minOrder: 30,
    rating: 4.7,
    reviews: 55,
    badge: "Freshly Cut",
    img: "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=600&h=400&fit=crop&auto=format",
    desc: "Fresh ogede agbagba (plantain) bunches cut to order from Akwa Ibom — one of Nigeria's largest plantain-producing states. Ripe (for dodo, bole, and plantain pottage) and unripe (for chips and plantain flour) options available. Consistency and volume guaranteed with 3-day advance order.",
    harvest: "2026-06-21",
    quality: "Grade A",
    method: "Traditional",
    verified: true,
  },
  {
    id: 12,
    name: "Wake Soya (Soybeans)",
    category: "Legumes",
    farmer: "Martha Davou",
    farmerInitial: "MD",
    location: "Shendam, Plateau State",
    state: "Plateau",
    price: 480,
    unit: "kg",
    qty: 3000,
    minOrder: 150,
    rating: 4.8,
    reviews: 112,
    img: "https://images.unsplash.com/photo-1562447457-579fc34967fb?w=600&h=400&fit=crop&auto=format",
    desc: "High-protein wake soya (soybeans) from Plateau State. Used for soy milk, awara (Hausa tofu), poultry feed, and industrial processing. Moisture content below 12%. Certified by FIIRO. Widely sourced by Chi Farms, OLAM, and local poultry farmers across Nigeria.",
    harvest: "2026-05-05",
    quality: "Grade A",
    method: "Conventional",
    verified: true,
  },
];

export interface CartItem extends Product {
  cartQty: number;
}

export const NIGERIAN_STATES = [
  "Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno",
  "Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe",
  "Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos",
  "Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto",
  "Taraba","Yobe","Zamfara",
];
